import type { AppSnapshot, Session } from "@/types/domain";

const now = Date.now();

const sessions: Session[] = [
  {
    schema_version: 1,
    id: "01KDEMOSESSION1",
    title: "Weekly product sync",
    project_id: "01KDEMOPROJECT",
    revision: 3,
    source: "recording",
    lifecycle: "ready",
    recovery_state: "none",
    created_at: new Date(now - 86_400_000).toISOString(),
    started_at: new Date(now - 86_400_000).toISOString(),
    stopped_at: new Date(now - 82_980_000).toISOString(),
    duration_ms: 3_420_000,
    microphone: null,
    system_output: null,
    artifacts: [],
    current_transcript_id: "01KDEMOTRANSCRIPT",
  },
  {
    schema_version: 1,
    id: "01KDEMOSESSION2",
    title: "Customer discovery — Rowan",
    project_id: null,
    revision: 1,
    source: "recording",
    lifecycle: "ready",
    recovery_state: "none",
    created_at: new Date(now - 172_800_000).toISOString(),
    started_at: new Date(now - 172_800_000).toISOString(),
    stopped_at: new Date(now - 170_160_000).toISOString(),
    duration_ms: 2_640_000,
    microphone: null,
    system_output: null,
    artifacts: [],
    current_transcript_id: "01KDEMOTRANSCRIPT2",
  },
  {
    schema_version: 1,
    id: "01KDEMOSESSION3",
    title: "Architecture notes",
    project_id: "01KDEMOPROJECT",
    revision: 1,
    source: "import",
    lifecycle: "needs_attention",
    recovery_state: "none",
    created_at: new Date(now - 259_200_000).toISOString(),
    started_at: null,
    stopped_at: null,
    duration_ms: 4_860_000,
    microphone: null,
    system_output: null,
    artifacts: [],
    current_transcript_id: null,
  },
];

export function createPreviewSnapshot(
  path = "~/Documents/OpenTranscribe",
  setupCompleted = true,
): AppSnapshot {
  return {
    library: {
      id: "01KDEMOLIBRARY",
      path,
      project_count: 2,
      session_count: sessions.length,
    },
    projects: [
      {
        schema_version: 1,
        id: "01KDEMOPROJECT",
        name: "Product",
        revision: 1,
        glossary: ["Tauri", "OpenTranscribe", "ScreenCaptureKit"],
        openai_profile_id: null,
        language_hint: null,
        created_at: new Date(now - 2_592_000_000).toISOString(),
        updated_at: new Date(now - 86_400_000).toISOString(),
      },
      {
        schema_version: 1,
        id: "01KDEMOPROJECT2",
        name: "Customer interviews",
        revision: 1,
        glossary: [],
        openai_profile_id: null,
        language_hint: null,
        created_at: new Date(now - 1_296_000_000).toISOString(),
        updated_at: new Date(now - 172_800_000).toISOString(),
      },
    ],
    recent_sessions: sessions,
    active_jobs: [
      {
        id: "01KDEMOJOB",
        session_id: "01KDEMOSESSION3",
        kind: "transcribe_local",
        state: "running",
        progress: {
          stage: "transcribing",
          completed_units: 1_920_000,
          total_units: 4_860_000,
          unit: "audio_ms",
          message: "Transcribing 32:00 of 1:21:00",
        },
        attempt: 1,
        error_message: null,
        created_at: new Date(now - 120_000).toISOString(),
        updated_at: new Date(now - 5_000).toISOString(),
      },
    ],
    settings: {
      revision: 1,
      setup_completed: setupCompleted,
      recording_mode: "record_only",
      openai_transcription_model: "gpt_transcribe",
      microphone_device_id: null,
      capture_system_audio: false,
      recording_project_selection: { kind: "automatic" },
      global_shortcut_enabled: false,
      global_shortcut: "command_or_control_shift_r",
      appearance: {
        theme: "system",
        reduced_motion: false,
      },
    },
  };
}
